module Style.Thing exposing (..)

-- Generated by elm-css-modules.

import Html exposing (Attribute)
import Html.Attributes exposing (class)


thing : Attribute msg
thing =
    class "_3jx9u6u1"


red : Attribute msg
red =
    class "_3EGu-319 _3jx9u6u1"


green : Attribute msg
green =
    class "_3FzV0jPC _3jx9u6u1"
