module Style.Alert exposing (..)

-- Generated by elm-css-modules.

import Html exposing (Attribute)
import Html.Attributes exposing (class)


alert : Attribute msg
alert =
    class "PGYl5Pf7"


primary : Attribute msg
primary =
    class "nx34pkJf PGYl5Pf7"


secondary : Attribute msg
secondary =
    class "_2kyrY1qK PGYl5Pf7"
