module Style.Button exposing (..)

-- Generated by elm-css-modules.

import Html exposing (Attribute)
import Html.Attributes exposing (class)


button : Attribute msg
button =
    class "HGj2cL1k"


primary : Attribute msg
primary =
    class "_2plXPmD7 HGj2cL1k"


secondary : Attribute msg
secondary =
    class "eMwOuNIU HGj2cL1k"
