module Style.Alert exposing (..)

-- Generated by elm-css-modules.

import Html exposing (Attribute)
import Html.Attributes exposing (class)


alert : Attribute msg
alert =
    class "_1Odp5TpB"


primary : Attribute msg
primary =
    class "_3_MEaE7o _1Odp5TpB"


secondary : Attribute msg
secondary =
    class "sG85UAcI _1Odp5TpB"
