module Style.Button exposing (..)

-- Generated by elm-css-modules.

import Html exposing (Attribute)
import Html.Attributes exposing (class)


button : Attribute msg
button =
    class "_3qxcqRqp"


primary : Attribute msg
primary =
    class "IxG4I30S _3qxcqRqp"


secondary : Attribute msg
secondary =
    class "_3RUmQNET _3qxcqRqp"
